name: List PR Changes

on:
  pull_request:
    branches:
      - master

jobs:
  list-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List changes
        run: |
          # Get the base and head commit hashes
          BASE_COMMIT=$(git rev-parse --short origin/${GITHUB_BASE_REF})
          HEAD_COMMIT=$(git rev-parse --short origin/${GITHUB_HEAD_REF})

          # Loop through each file changed in the PR
          git diff --name-only ${BASE_COMMIT}..${HEAD_COMMIT} | while read file; do
            echo "File: $file"
            echo "Diff:"
            git diff ${BASE_COMMIT}..${HEAD_COMMIT} -- $file
            echo "------------------------"
          done

